Hw10 program optimization
aleks-papushin/otus_go_hw pull request #10
Opened 2024-08-19 00:05 UTC by aleks-papushin

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-08-19 04:46 UTC, vladislavmass requested changes

2024-08-19 04:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +var targetDomain string
Функция `GetDomainStat(r io.Reader, domain string) (DomainStat, error)` может быть запущена в нескольких потоков и при таком использование мы получим гонку данных из за этой переменной уровня пакета

2024-08-19 04:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +			domainsCh <- strings.ToLower(strings.Split(userEmail.Email, "@")[1])
Если пользователь забыл добавить символ собаки то тут будет паника.

2024-08-19 04:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +			if strings.Split(e, ".")[1] == targetDomain {
Опять таки потенциальная паника за место безопасного HasSuffix

2024-08-19 04:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +			if strings.Split(e, ".")[1] == targetDomain {
Опять таки. Мы забываем тут о том, что домен может быть например .ru.com

2024-08-19 04:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +				fmt.Println(err)
Что будет если у меня есть база на 100 000 емайлов и ну скажем на 2 произошла ошибка анмаршлинга json.  я тат выхожу из функции через return не закрывая канал и получается что все последующие каналы ждут пока это горутина что то запишет, а предыдущая горутина забила буфер и ждет пока из буфера считают

2024-08-24 13:55 UTC, aleks-papushin commented on hw10_program_optimization/stats.go
> +var targetDomain string
Порефакторил на однопоточный вариант

2024-08-24 13:55 UTC, aleks-papushin commented on hw10_program_optimization/stats.go
> +			domainsCh <- strings.ToLower(strings.Split(userEmail.Email, "@")[1])
Да, точно, пофиксил

2024-08-24 14:01 UTC, aleks-papushin commented on hw10_program_optimization/stats.go
> +			if strings.Split(e, ".")[1] == targetDomain {
Верно. Поменял логику парсинга домена

2024-08-24 14:02 UTC, aleks-papushin commented on hw10_program_optimization/stats.go
> +				fmt.Println(err)
Спасибо, пофиксил

2024-08-24 14:22 UTC, vladislavmass approved these changes

2024-08-24 14:22 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +			strings.Contains(email, "@") {
В данном случае все таки интереснее выглядит вариант 
```
    data:=strings.Split(email, "@")
    if len(data)>1
```
Так как что `Split` что `Contains` это поиск в строке. 2 поиска в строке явно тяжелее проверки длинны

2024-08-25 13:10 UTC, merged