Hw04 lru cache
aleks-papushin/otus_go_hw pull request #4
Opened 2024-04-28 21:30 UTC by aleks-papushin

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-05-04 20:19 UTC, vladislavmass requested changes

2024-05-04 20:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		i.Next.Prev = nil
Тут есть паника. Если мы удаляем из списка единственный элемент то i.Prev==nil и i.Next==nil.

2024-05-04 20:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		i.Prev.Next = nil
Тоже самое что и выше

2024-05-04 20:19 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if c.queue.Len() > c.capacity {
Размер очереди не должен превышать капасити даже на пару тактов

2024-05-04 20:49 UTC, aleks-papushin commented on hw04_lru_cache/list.go
> +		i.Next.Prev = nil
Поправил и добавил тест. Спасибо!

2024-05-04 20:49 UTC, aleks-papushin commented on hw04_lru_cache/cache.go
> +	if c.queue.Len() > c.capacity {
Исправил

2024-05-04 20:54 UTC, aleks-papushin commented on hw04_lru_cache/list.go
> +		i.Prev.Next = nil
Тоже исправлено. Теперь оба места покрылись условием, которое проверяется в начале функции

2024-05-05 06:17 UTC, vladislavmass requested changes

2024-05-05 06:17 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	c.items = make(map[Key]*ListItem)
Было бы хорошо сразу указать размер мапы, раз мы его знаем

2024-05-05 06:17 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +		return
Это конечно решает ситуацию с паниками. Но как теперь удалить из мамы единственный элемент? Ведь после выполнения remove на единственном элементе front и back продолжат на него указывать.

2024-05-05 10:37 UTC, aleks-papushin commented on hw04_lru_cache/list.go
> +		return
Да, это конечно некорректно. Исправил. Заменил if'ы в данном методе на switch конструкцию. И добавил в тесты проверку на то, что после удаления единственного элемента front и back становятся nil

2024-05-05 10:45 UTC, aleks-papushin commented on hw04_lru_cache/cache.go
> +	c.items = make(map[Key]*ListItem)
Владислав, здесь уточните, пожалуйста. Какой именно размер вы имеете ввиду? 
Ведь по дефолту мапа создастся с размером 0 и, кажется, что при очистке кэша это будет правильно делать.

2024-05-05 11:06 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	c.items = make(map[Key]*ListItem)
Так у нас есть максимальный размер мапы в виде капасити, предлагаю его и задать как размер мапы

2024-05-05 11:07 UTC, vladislavmass approved these changes

2024-05-05 12:48 UTC, aleks-papushin commented on hw04_lru_cache/cache.go
> +	c.items = make(map[Key]*ListItem)
Да, конечно! Не подумал об этом. Логично только так и делать, раз изначально мы в конструкторе задаем capacity.

2024-05-05 12:50 UTC, merged