Hw07 file copying
aleks-papushin/otus_go_hw pull request #7
Opened 2024-06-16 21:04 UTC by aleks-papushin

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-17 04:53 UTC, vladislavmass requested changes

2024-06-17 04:53 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if ok := strings.HasSuffix(fromPath, ".txt"); !ok {
Откуда у нас взялось вот это ограничение? Утилита должна уметь копировать файлы и не важно текст это, фильмы, музыка или бинарные файлы

2024-06-17 04:53 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		time.Sleep(time.Millisecond * 400) // throttle in purpose to see progress bar animation in terminal
Подумайте сколько код проспит при копирование файла весом в 4 гб?

2024-06-17 21:06 UTC, aleks-papushin commented on hw07_file_copying/copy.go
> +		time.Sleep(time.Millisecond * 400) // throttle in purpose to see progress bar animation in terminal
Владислав, это по сути для дебаггинга и для иллюстрации. Оставил, чтобы было видно, что прогресс бар двигается. В первоначальном варианте у меня прогресс бар работал неправильно и показывал сразу 100%. Я не итерировался по файлу, считывая в небольшой буфер, а считывал разом весь файл в буфер. Прогресс бар сразу показывал 100%. Когда я изменил на текущую реализацию, я обнаружил, что прогресс бар ведет себя так же, как и раньше - мгновенно оказывается на 100%. Поэтому добавил это, чтобы было видно, что он на самом деле работает. Уберу.

2024-06-17 21:08 UTC, aleks-papushin commented on hw07_file_copying/copy.go
> +	if ok := strings.HasSuffix(fromPath, ".txt"); !ok {
Там в изначально предоставленном коде есть ошибка ErrUnsupportedFile. Я только такой придумал вариант для ее использования.

2024-06-18 19:08 UTC, vladislavmass approved these changes

2024-06-18 20:51 UTC, merged