Hw08 envdir tool
aleks-papushin/otus_go_hw pull request #8
Opened 2024-06-30 22:20 UTC by aleks-papushin

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-07-01 11:01 UTC, vladislavmass requested changes

2024-07-01 11:01 UTC, vladislavmass commented on hw08_envdir_tool/main.go
> +	env, _ := ReadDir(os.Args[1])
Мы точно хотим выполнять код, если произошла ошибка?

2024-07-01 11:01 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +		func() {
Не вижу обработки символа `=` в имени файла.

2024-07-06 15:31 UTC, aleks-papushin commented on hw08_envdir_tool/main.go
> +	env, _ := ReadDir(os.Args[1])
Добавил здесь обработку

2024-07-06 15:31 UTC, aleks-papushin commented on hw08_envdir_tool/env_reader.go
> +		func() {
Добавил

2024-07-06 15:37 UTC, aleks-papushin commented on hw08_envdir_tool/main.go
> +	RunCmd(os.Args[2:], env)
Да, верно, добавил правку

2024-07-06 15:41 UTC, vladislavmass approved these changes

2024-07-06 20:12 UTC, merged